// Preload（CJS）—— Electron preload 加载器只支持 CommonJS
const { contextBridge, ipcRenderer } = require('electron');

// 暴露受限 API 给渲染进程（不直接暴露 Node）
contextBridge.exposeInMainWorld('api', {
  collect: (opts) => ipcRenderer.invoke('collect', opts),
  collectMultiple: (payload) => ipcRenderer.invoke('collect-multiple', payload),
  collectCancel: () => ipcRenderer.invoke('collect-cancel'),
  onCollectProgress: (cb) => ipcRenderer.on('collect-progress', (_e, payload) => cb && cb(payload)),
  autoCf: (opts) => ipcRenderer.invoke('auto-cf', opts),
  collectFromHtml: (payload) => ipcRenderer.invoke('collect-from-html', payload),
  cached: () => ipcRenderer.invoke('cached'),
  import: (payload) => ipcRenderer.invoke('import', payload),
  clearIme: () => ipcRenderer.invoke('clear-ime'),
  undoIme: (payload) => ipcRenderer.invoke('undo-ime', payload),
  resolveOrders: (payload) => ipcRenderer.invoke('resolve-orders', payload),
  batches: () => ipcRenderer.invoke('batches'),
  batchesUsage: (payload) => ipcRenderer.invoke('batches-usage', payload),
  loadBatch: (payload) => ipcRenderer.invoke('batch-load', payload),
  saveUsed: (payload) => ipcRenderer.invoke('used-save', payload),
  loadConfig: () => ipcRenderer.invoke('config-load'),
  saveConfig: (cfg) => ipcRenderer.invoke('config-save', cfg),
  configCheck: () => ipcRenderer.invoke('config-check'),
  configIsolate: (issues) => ipcRenderer.invoke('config-isolate', { issues }),
  loadBindings: () => ipcRenderer.invoke('bindings-load'),
  saveBindings: (payload) => ipcRenderer.invoke('bindings-save', payload),
  bindingLimits: () => ipcRenderer.invoke('binding-limits'),
  saveGlobalBindings: (payload) => ipcRenderer.invoke('bindings-save-global', payload),
  shortcutsLoad: () => ipcRenderer.invoke('shortcuts-load'),
  shortcutsSave: (payload) => ipcRenderer.invoke('shortcuts-save', payload),
  deleteBatch: (payload) => ipcRenderer.invoke('batch-delete', payload),
  loadLang: (payload) => ipcRenderer.invoke('lang-load', payload),
  langList: () => ipcRenderer.invoke('lang-list'),
  systemTheme: () => ipcRenderer.invoke('system-theme'),
  close: () => ipcRenderer.send('close'),
  minimize: () => ipcRenderer.send('minimize'),
  toggleAlwaysOnTop: (opts) => ipcRenderer.invoke('toggle-always-on-top', opts),
  setGlobalShortcuts: (payload) => ipcRenderer.invoke('set-global-shortcuts', payload),
  onTriggerShortcut: (cb) => ipcRenderer.on('trigger-shortcut', (_e, payload) => cb && cb(payload)),
  copyText: (payload) => ipcRenderer.invoke('copy-text', payload),
  apiStatus: () => ipcRenderer.invoke('api-status'),
  apiToggle: () => ipcRenderer.invoke('api-toggle'),
  openExternal: (payload) => ipcRenderer.invoke('open-external', payload),
  // 本地 HTTP API 操作后，主进程通知渲染进程刷新界面
  onApiRefresh: (cb) => ipcRenderer.on('api-refresh', (_e) => cb && cb()),
  // 版本更新 / 回滚
  updaterCheck: () => ipcRenderer.invoke('updater:check'),
  updaterList: () => ipcRenderer.invoke('updater:list'),
  updaterCurrent: () => ipcRenderer.invoke('updater:current'),
  updaterSwitch: (payload) => ipcRenderer.invoke('updater:switch', payload),
  updaterRestart: () => ipcRenderer.invoke('updater:restart'),
  onUpdaterProgress: (cb) => ipcRenderer.on('updater-progress', (_e, p) => cb && cb(p)),
  onUpdaterLog: (cb) => ipcRenderer.on('updater-log', (_e, p) => cb && cb(p)),
});
