// 内置中英双语语言对照表（强制写入代码，作为 lang 文件异常时的本地回退源）。
// 由 data/lang/zh-CN.json 与 data/lang/en.json 生成 —— 官方语言包有改动时请重新运行生成脚本。
export const BUILTIN_CODES = ['zh-CN', 'en'];

export const BUILTIN_LANGS = {
  'zh-CN':   {
    "language": "中文简体",
    "app.title": "日文名 · 输入法短语",
    "tip.settings": "设置：语言与主题切换、全局绑定管理",
    "tip.refresh": "刷新当前界面所有内容（配置、批次、列表、统计）",
    "tip.pin": "固定窗口到最前面（始终置顶），再次点击取消固定",
    "tip.min": "最小化窗口",
    "tip.close": "关闭工具",
    "gender.G": "女名",
    "gender.B": "男名",
    "gender.U": "中性",
    "tip.gender": "选择生成名字的性别倾向：女名 / 男名 / 中性",
    "pop.popular": "热门",
    "pop.unique": "独特",
    "pop.trending": "流行",
    "tip.popularity": "选择名字风格：热门 / 独特 / 流行",
    "btn.fetch": "⚡抓取",
    "tip.fetch": "从 namechef 抓取一批日文名并保存到本地批次",
    "stat.kanji": "汉字",
    "stat.romaji": "罗马音",
    "stat.hiragana": "平假名",
    "stat.detail": "未用 {unused} / 已用 {used} / 共 {total}",
    "stat.noData": "无数据",
    "stat.empty": "未使用 — / 已用 — / 共用 —",
    "lbl.batch": "数据批次",
    "tip.batch": "选择要操作的数据批次（按抓取时间命名）",
    "lbl.phraseField": "短语字段",
    "tip.phraseField": "最终写进输入法候选栏的字段：汉字 / 罗马音 / 平假名",
    "field.kanji": "汉字",
    "field.romaji": "罗马音",
    "field.hiragana": "平假名",
    "lbl.binding": "绑定方式",
    "tip.binding": "把名字映射到输入法编码的方式：手动 / 手动(全局) / 英文键位顺序(26) / 英文键位流转顺序(12)",
    "bind.manual": "手动",
    "bind.manualGlobal": "手动（全局）",
    "tip.bindManualGlobal": "使用全局默认绑定（__global__）作为编码来源，无需逐行填写；未设置全局绑定的行将留空",
    "tip.globalCodeReadOnly": "该编码来自全局默认绑定（只读），请到「设置→存当前批次绑定为全局」进行管理",
    "tip.bindManualDetail": "手动模式：逐行输入拼音编码（如 q、sakura），每行独立设置。无数量限制，适合精确控制每个名字的输入法编码。未填写的行导入时将留空",
    "lbl.orderPos": "候选位置",
    "tip.orderMode": "固定：所有短语都用同一候选位置（右侧可在固定时改成 =2、=3…）；自动：导入时检测「同拼音+同位置」冲突并自动 +1",
    "order.fixed": "固定(=1)",
    "order.auto": "自动(冲突检测)",
    "tip.orderValue": "固定模式下的候选窗口位置，可改成 2、3……数值越大越靠后",
    "lbl.count": "导入数量",
    "tip.count": "本次「一键导入」要写入的名字条数",
    "btn.import": "一键导入",
    "tip.import": "把当前批次前 N 条名字写入微软拼音「用户自定义短语」",
    "btn.clear": "一键清除",
    "tip.clear": "清空微软拼音词库里的全部自定义短语（可用「撤回」恢复）",
    "btn.undo": "撤回",
    "tip.undo": "撤回上一次的导入或清除操作",
    "tip.hideStatus": "隐藏底部提示栏（出现新提示时会自动重新显现）",
    "set.lang": "语言",
    "set.theme": "主题",
    "theme.light": "亮色",
    "theme.dark": "暗色",
    "theme.system": "跟随系统",
    "set.globalSave": "存当前批次绑定为全局",
    "tip.globalSave": "把当前批次的手动绑定保存为全局默认；其他批次未手动填写时自动套用",
    "set.globalClear": "清除全局默认绑定",
    "tip.globalClear": "删除 bindings.json 中的全局默认绑定",
    "msg.globalSaved": "已保存全局默认绑定（{n} 行）",
    "msg.globalNone": "当前批次没有可保存的手动绑定",
    "msg.globalCleared": "已清除全局默认绑定",
    "msg.refreshed": "界面已刷新",
    "msg.langChanged": "语言已切换：{lang}",
    "list.empty": "暂无数据，点「⚡抓取」一键获取",
    "tip.lightUsed": "该名字已使用（点击标记为未使用）",
    "tip.lightUnused": "该名字未使用（点击标记为已使用）",
    "ph.binding": "绑定",
    "tip.codeInput": "手动绑定：输入该名字对应的拼音编码（如 q、sakura），会写入输入法候选栏",
    "tip.globalBinding": "该编码来自全局默认绑定，输入新值可覆盖本批次",
    "tip.lock": "锁定本行绑定，排序变化后该编码保持不动（状态会持久化）",
    "tip.addAlias": "为当前名字增加一个别名绑定（另一个编码指向同一短语）",
    "ph.alias": "别名{n}",
    "tip.aliasInput": "输入别名编码（如该名字的另一个罗马音）",
    "tip.aliasDel": "删除此别名绑定",
    "msg.copied": "已复制：{text}",
    "msg.copyFail": "复制失败：{text}",
    "msg.batchLoaded": "已加载批次 {batch}：{n} 条",
    "msg.cfChallenge": "正在通过 Cloudflare 质询…（若弹出验证窗口请点一下）",
    "msg.parsing": "已通过质询，解析页面中…",
    "msg.gotCookie": "已获取 Cookie，抓取中…",
    "msg.fetchOk": "✅ 抓取成功：{n} 个名字，已保存{info}",
    "msg.fetchFail": "抓取失败：{err}",
    "msg.noImport": "没有可导入的名字",
    "confirm.usedInSlice": "即将导入的 {count} 条中包含 {used} 条已使用名称。\n\n点「确定」自动将导入数量调整为 {adj}（仅导入未使用名称）并继续；\n点「取消」中止本次导入。",
    "confirm.allUsed": "当前批次名称已全部使用。\n\n是否仍按原数量导入前 {count} 条已使用名称？",
    "msg.cancelled": "已取消导入",
    "msg.checkingConflict": "正在检测候选位置冲突…",
    "line.orderAdjust": "  拼音「{code}」→ 短语「{word}」：位置 {from} → {to}",
    "confirm.orderAdjust": "检测到 {n} 处候选位置冲突，将自动调整：\n\n{lines}\n\n点「确定」按调整后的位置导入；点「取消」中止。",
    "msg.conflictFail": "⚠️ 冲突检测失败（{err}），将以固定位置=1 导入",
    "msg.importing": "生成 .dat 并写入输入法…",
    "msg.importOk": "已导入 {n} 条 → {files} | IME 已重载",
    "msg.importPartial": "已导入 {n} 条（文件已写入）→ {files} | ⚠️ IME 未完全重载（{method}），请确认 UAC 弹窗或重启输入法",
    "msg.importFail": "导入失败：{err}",
    "confirm.clear": "确定要清除所有用户自定义短语吗？\n\n此操作将清空微软拼音词库中的全部自定义词条！",
    "msg.clearing": "正在清除所有自定义短语…",
    "msg.clearOk": "已清除所有自定义短语（原 {n} 条）→ {target} | IME 已重载",
    "msg.clearPartial": "已清除所有自定义短语（原 {n} 条，文件已写入） | ⚠️ IME 未完全重载（{method}），请确认 UAC 弹窗或重启输入法",
    "msg.clearFail": "清除失败：{err}",
    "msg.noUndo": "无可撤回的操作",
    "confirm.undoClear": "确定要撤回上次的「一键清除」吗？\n\n将恢复清除前的词库备份。",
    "confirm.undoImport": "确定要撤回上次的导入吗？\n\n将移除本次导入的 {n} 条已使用标记，并恢复词库备份。",
    "msg.undoing": "正在撤回…",
    "msg.undoOk": "已撤回 → {target} | IME 已重载",
    "msg.undoPartial": "已撤回（文件已恢复）→ {target} | ⚠️ IME 未完全重载（{method}），请确认 UAC 弹窗或重启输入法",
    "msg.undoFail": "撤回失败：{err}",
    "msg.pinned": "已固定到窗口最前面",
    "msg.unpinned": "已取消固定（不再置顶）",
    "msg.pinFail": "切换置顶状态失败",
    "msg.cacheLoaded": "已加载缓存 {n} 条",
    "msg.locked": "已锁定第 {row} 行绑定（编码已固定，输入框禁用）",
    "msg.unlocked": "已解锁第 {row} 行绑定（输入框可编辑）",
    "msg.lockNeedCode": "请先填写绑定编码，再锁定本行",
    "bind.qwerty": "英文键位顺序",
    "bind.qwerFlow": "英文键位流转顺序",
    "tip.bindQwerty": "英文键位顺序：qwertyuiopasdfghjklzxcvbnm，共 26 位，导入数量不得超过 26",
    "tip.bindQwerFlow": "英文键位流转顺序：qwerasdfzxcv，共 12 位，导入数量不得超过 12",
    "set.batchClear": "删除当前批次绑定",
    "tip.batchClear": "清空当前批次的全部手动绑定（不影响其他批次）",
    "tip.countDec": "减少数量（右击：调整至最小）",
    "tip.countInc": "增加数量（右击：调整至最大）",
    "msg.batchBindCleared": "已删除当前批次 {batch} 的全部手动绑定",
    "msg.noBatch": "尚未选择数据批次",
    "msg.batchLost": "上次打开的数据批次「{batch}」已不可用，请手动选择数据批次",
    "dialog.manualBindShort.title": "绑定数量不足",
    "dialog.manualBindShort.body": "当前选择「手动」绑定模式，导入数量为 {count} 条，但仅有 {coded} 行填写了编码。\n\n缺少编码的 {missing} 行将无法生成有效的输入法短语。请选择处理方式：",
    "dialog.manualBindShort.autoQwerty": "自动补全(qwerty)并继续",
    "dialog.manualBindShort.force": "强制继续（空编码）",
    "dialog.manualBindShort.cancel": "取消导入",
    "msg.autoAssigned": "已为 {n} 行自动分配 qwerty 编码",
    "dialog.importPreview.title": "导入预览",
    "dialog.importPreview.confirm": "确认导入",
    "dialog.importPreview.cancel": "取消",
    "dialog.importPreview.skip": "此后不再提醒",
    "dialog.configError.title": "配置文件异常",
    "dialog.configError.desc": "检测到以下配置文件损坏或无法解析，已跳过并改用默认配置。可将其隔离（重命名为 _error_+时间戳）后用默认配置重新加载。",
    "dialog.configError.range": "异常配置文件范围：",
    "dialog.configError.isolate": "隔离并重载新的配置文件",
    "dialog.configError.ignore": "忽略并继续",
    "msg.configIsolated": "已隔离 {n} 个损坏配置文件，已用默认配置重新加载",
    "msg.configIsolateFail": "{n} 个配置文件隔离失败（可能为只读资源，如语言包），请重新安装程序",
    "set.shortcuts": "快捷键",
    "act.fetch": "抓取",
    "act.import": "一键导入",
    "act.clear": "一键清除",
    "act.undo": "撤回",
    "act.toggleField": "切换短语字段",
    "msg.fieldSwitched": "已切换到短语字段：{field}",
    "act.fetch.tip": "调用 window.api.capture()（当 window.api 未暴露时回退到 window.__appActions.capture()），即可触发「抓取」：从 namechef 抓取一批日文名并存入当前批次。效果与按下 Alt+X 完全一致。",
    "act.import.tip": "调用 window.api.doImport()（或 window.__appActions.doImport()）触发「一键导入」：将当前批次前 N 条名字按所选绑定方式写入输入法自定义短语。等价于按下 Alt+V。",
    "act.clear.tip": "调用 window.api.doClear()（或 window.__appActions.doClear()）触发「一键清除」：清空输入法词库里的全部自定义短语。等价于按下 Alt+C，可用「撤回」恢复。",
    "act.undo.tip": "调用 window.api.doUndo()（或 window.__appActions.doUndo()）触发「撤回」：撤销上一次导入或清除操作。等价于按下 Alt+Z。",
    "act.toggleField.tip": "调用 window.api.togglePhraseField()（或 window.__appActions.togglePhraseField()）触发「切换短语字段」：在 汉字 / 罗马音 / 平假名 之间循环切换当前短语字段。等价于按下 Alt+B。",
    "set.shortcut.edit": "录制",
    "set.shortcut.editing": "停止",
    "set.shortcut.enabled": "启用",
    "set.shortcut.disabled": "禁用",
    "set.shortcut.disableTip": "点击启用 / 禁用该快捷键",
    "set.api": "本地API",
    "set.api.off": "未启用",
    "set.api.on": "已启用 · {url}",
    "set.api.doc": "文档",
    "set.api.doc.link": "API 文档地址",
    "shortcut.recording": "请按下快捷键组合（最多 3 个按键）…",
    "shortcut.invalid": "快捷键组合最多 3 个按键，本次未保存。",
    "shortcut.captured": "已保存快捷键：{combo}",
    "batch.ctx.delete": "删除批次",
    "dialog.deleteBatch.title": "删除数据批次",
    "dialog.deleteBatch.body": "确定删除批次「{batch}」吗？删除后该批次的数据及其关联绑定方式将一并移除，且不可恢复。",
    "dialog.deleteBatch.confirm": "删除",
    "dialog.deleteBatch.cancel": "取消",
    "msg.batchDeleted": "已删除批次：{batch}",
    "msg.batchDeleteFailed": "删除失败：{msg}",
    "msg.apiToggleFail": "API 启停切换失败：{err}",
    "closeModal.title": "关闭应用",
    "closeModal.body": "请选择操作：",
    "closeModal.minimize": "隐藏图标",
    "closeModal.closeApp": "关闭应用",
    "closeModal.remember": "记住我的选择",
    "tip.info": "关于本工具",
    "about.title": "关于",
    "about.github": "GitHub 仓库",
    "about.version": "版本",
    "about.author": "作者",
    "about.copyright": "版权",
    "about.close": "关闭"
  },
  'en':   {
    "language": "English",
    "app.title": "Japanese Names · IME Phrases",
    "tip.settings": "Settings: language, theme, and global bindings",
    "tip.refresh": "Refresh everything on screen (config, batches, list, stats)",
    "tip.pin": "Pin window always on top; click again to unpin",
    "tip.min": "Minimize window",
    "tip.close": "Close the tool",
    "gender.G": "Female",
    "gender.B": "Male",
    "gender.U": "Neutral",
    "tip.gender": "Gender preference for generated names: female / male / neutral",
    "pop.popular": "Popular",
    "pop.unique": "Unique",
    "pop.trending": "Trending",
    "tip.popularity": "Name style: popular / unique / trending",
    "btn.fetch": "⚡Fetch",
    "tip.fetch": "Fetch a batch of Japanese names from namechef and save locally",
    "stat.kanji": "Kanji",
    "stat.romaji": "Romaji",
    "stat.hiragana": "Hiragana",
    "stat.detail": "Unused {unused} / Used {used} / Total {total}",
    "stat.noData": "No data",
    "stat.empty": "unused — / used — / total —",
    "lbl.batch": "Batch",
    "tip.batch": "Choose the data batch to work with (named by fetch time)",
    "lbl.phraseField": "Phrase field",
    "tip.phraseField": "Field written to the IME candidate bar: kanji / romaji / hiragana",
    "field.kanji": "Kanji",
    "field.romaji": "Romaji",
    "field.hiragana": "Hiragana",
    "lbl.binding": "Binding",
    "tip.binding": "How names map to IME codes: manual / manual(global) / QWERTY key order (26) / QWERTY flow order (12)",
    "bind.manual": "Manual",
    "bind.manualGlobal": "Manual (Global)",
    "tip.bindManualGlobal": "Uses global default bindings (__global__) as code source; no per-row entry needed. Rows without global bindings will be left empty",
    "tip.globalCodeReadOnly": "This code comes from global default bindings (read-only). Manage via Settings → Save batch bindings as global",
    "tip.bindManualDetail": "Manual mode: enter pinyin code per row (e.g. q, sakura), each row independent. No count limit, ideal for precise control over each name's IME code. Empty rows will be imported with blank codes",
    "lbl.orderPos": "Candidate pos.",
    "tip.orderMode": "Fixed: all phrases use the same candidate position (editable when fixed); Auto: detect same-code+same-position conflicts at import and auto +1",
    "order.fixed": "Fixed (=1)",
    "order.auto": "Auto (conflict check)",
    "tip.orderValue": "Candidate window position in fixed mode; larger = further back",
    "lbl.count": "Import count",
    "tip.count": "Number of names to write in this import",
    "btn.import": "Import",
    "tip.import": "Write the first N names of the current batch into Microsoft Pinyin user-defined phrases",
    "btn.clear": "Clear all",
    "tip.clear": "Remove all user-defined phrases from the Microsoft Pinyin lexicon (undo available)",
    "btn.undo": "Undo",
    "tip.undo": "Undo the last import or clear operation",
    "tip.hideStatus": "Hide the bottom status bar (it reappears on new messages)",
    "set.lang": "Language",
    "set.theme": "Theme",
    "theme.light": "Light",
    "theme.dark": "Dark",
    "theme.system": "System",
    "set.globalSave": "Save batch bindings as global",
    "tip.globalSave": "Save the current batch's manual bindings as global defaults, applied when a batch has no manual entry",
    "set.globalClear": "Clear global bindings",
    "tip.globalClear": "Remove the global default bindings from bindings.json",
    "msg.globalSaved": "Global default bindings saved ({n} rows)",
    "msg.globalNone": "No manual bindings in the current batch to save",
    "msg.globalCleared": "Global default bindings cleared",
    "msg.refreshed": "UI refreshed",
    "msg.langChanged": "Language switched: {lang}",
    "list.empty": "No data. Click \"⚡Fetch\" to get names",
    "tip.lightUsed": "Used (click to mark as unused)",
    "tip.lightUnused": "Unused (click to mark as used)",
    "ph.binding": "code",
    "tip.codeInput": "Manual binding: enter the pinyin code for this name (e.g. q, sakura); it goes into the IME candidates",
    "tip.globalBinding": "This code comes from the global default bindings; type a new value to override for this batch",
    "tip.lock": "Lock this row's binding; it stays put when sorting changes (persisted)",
    "tip.addAlias": "Add an alias binding (another code pointing to the same phrase)",
    "ph.alias": "alias {n}",
    "tip.aliasInput": "Enter the alias code (e.g. another romaji of this name)",
    "tip.aliasDel": "Delete this alias binding",
    "msg.copied": "Copied: {text}",
    "msg.copyFail": "Copy failed: {text}",
    "msg.batchLoaded": "Batch {batch} loaded: {n} entries",
    "msg.cfChallenge": "Passing Cloudflare challenge… (click the popup if one appears)",
    "msg.parsing": "Challenge passed, parsing page…",
    "msg.gotCookie": "Cookie obtained, fetching…",
    "msg.fetchOk": "✅ Fetched {n} names, saved{info}",
    "msg.fetchFail": "Fetch failed: {err}",
    "msg.noImport": "No names to import",
    "confirm.usedInSlice": "The {count} entries to import include {used} already-used names.\n\nOK: adjust the import count to {adj} (unused only) and continue;\nCancel: abort this import.",
    "confirm.allUsed": "All names in this batch are already used.\n\nImport the first {count} used names anyway?",
    "msg.cancelled": "Import cancelled",
    "msg.checkingConflict": "Checking candidate position conflicts…",
    "line.orderAdjust": "  code \"{code}\" → phrase \"{word}\": position {from} → {to}",
    "confirm.orderAdjust": "{n} candidate position conflicts detected; they will be auto-adjusted:\n\n{lines}\n\nOK: import with adjusted positions; Cancel: abort.",
    "msg.conflictFail": "⚠️ Conflict check failed ({err}); importing with fixed position = 1",
    "msg.importing": "Generating .dat and writing to IME…",
    "msg.importOk": "Imported {n} entries → {files} | IME reloaded",
    "msg.importPartial": "Imported {n} entries (files written) → {files} | ⚠️ IME not fully reloaded ({method}); confirm the UAC prompt or restart the IME",
    "msg.importFail": "Import failed: {err}",
    "confirm.clear": "Remove ALL user-defined phrases?\n\nThis empties every custom entry in the Microsoft Pinyin lexicon!",
    "msg.clearing": "Clearing all user-defined phrases…",
    "msg.clearOk": "Cleared all phrases (was {n}) → {target} | IME reloaded",
    "msg.clearPartial": "Cleared all phrases (was {n}, files written) | ⚠️ IME not fully reloaded ({method}); confirm the UAC prompt or restart the IME",
    "msg.clearFail": "Clear failed: {err}",
    "msg.noUndo": "Nothing to undo",
    "confirm.undoClear": "Undo the last \"Clear all\"?\n\nThe lexicon backup taken before clearing will be restored.",
    "confirm.undoImport": "Undo the last import?\n\nThe {n} used-marks added by that import will be removed and the lexicon backup restored.",
    "msg.undoing": "Undoing…",
    "msg.undoOk": "Undone → {target} | IME reloaded",
    "msg.undoPartial": "Undone (files restored) → {target} | ⚠️ IME not fully reloaded ({method}); confirm the UAC prompt or restart the IME",
    "msg.undoFail": "Undo failed: {err}",
    "msg.pinned": "Window pinned on top",
    "msg.unpinned": "Window unpinned (no longer on top)",
    "msg.pinFail": "Failed to toggle always-on-top",
    "msg.cacheLoaded": "Loaded {n} cached entries",
    "msg.locked": "Row {row} binding locked (code pinned, input disabled)",
    "msg.unlocked": "Row {row} binding unlocked (input editable)",
    "msg.lockNeedCode": "Enter a binding code before locking this row",
    "bind.qwerty": "QWERTY key order",
    "bind.qwerFlow": "QWERTY flow order",
    "tip.bindQwerty": "English key order: qwertyuiopasdfghjklzxcvbnm, 26 keys total, import count must not exceed 26",
    "tip.bindQwerFlow": "English key flow order: qwerasdfzxcv, 12 keys total, import count must not exceed 12",
    "set.batchClear": "Delete current batch bindings",
    "tip.batchClear": "Clear all manual bindings of the current batch (other batches unaffected)",
    "tip.countDec": "Decrease count (right-click: set to minimum)",
    "tip.countInc": "Increase count (right-click: set to maximum)",
    "msg.batchBindCleared": "Cleared all manual bindings of batch {batch}",
    "msg.noBatch": "No data batch selected",
    "msg.batchLost": "The last opened batch \"{batch}\" is no longer available. Please select a batch manually.",
    "dialog.manualBindShort.title": "Insufficient bindings",
    "dialog.manualBindShort.body": "\"Manual\" binding mode is selected with import count = {count}, but only {coded} rows have codes entered.\n\nThe {missing} rows without codes cannot generate valid IME phrases. Choose how to proceed:",
    "dialog.manualBindShort.autoQwerty": "Auto-fill (QWERTY) & continue",
    "dialog.manualBindShort.force": "Force continue (empty codes)",
    "dialog.manualBindShort.cancel": "Cancel import",
    "msg.autoAssigned": "Auto-assigned QWERTY codes to {n} rows",
    "dialog.importPreview.title": "Import Preview",
    "dialog.importPreview.confirm": "Confirm Import",
    "dialog.importPreview.cancel": "Cancel",
    "dialog.importPreview.skip": "Don't remind me again",
    "dialog.configError.title": "Config Files Corrupted",
    "dialog.configError.desc": "The following config files are corrupted or unparsable. They were skipped and defaults are used. You can isolate them (rename to _error_+timestamp) and reload with defaults.",
    "dialog.configError.range": "Corrupted config files:",
    "dialog.configError.isolate": "Isolate and reload with defaults",
    "dialog.configError.ignore": "Ignore and continue",
    "msg.configIsolated": "Isolated {n} corrupted config files; reloaded with defaults",
    "msg.configIsolateFail": "{n} config files failed to isolate (may be read-only, e.g. language packs); please reinstall",
    "set.shortcuts": "Shortcuts",
    "act.fetch": "Fetch",
    "act.import": "Import",
    "act.clear": "Clear",
    "act.undo": "Undo",
    "act.toggleField": "Toggle field",
    "msg.fieldSwitched": "Switched phrase field to: {field}",
    "act.fetch.tip": "Call window.api.capture() (falls back to window.__appActions.capture() when window.api is unavailable) to trigger Fetch: scrape a batch of Japanese names from namechef and store them in the current batch. Identical to pressing Alt+X.",
    "act.import.tip": "Call window.api.doImport() (or window.__appActions.doImport()) to trigger One-click Import: write the first N names of the current batch into the IME custom phrases using the selected binding. Same as pressing Alt+V.",
    "act.clear.tip": "Call window.api.doClear() (or window.__appActions.doClear()) to trigger One-click Clear: remove all custom phrases from the IME dictionary. Same as Alt+C; undoable via Undo.",
    "act.undo.tip": "Call window.api.doUndo() (or window.__appActions.doUndo()) to trigger Undo: revert the last import or clear operation. Same as pressing Alt+Z.",
    "act.toggleField.tip": "Call window.api.togglePhraseField() (or window.__appActions.togglePhraseField()) to trigger Toggle Phrase Field: cycle the current phrase field among Kanji / Romaji / Hiragana. Same as pressing Alt+B.",
    "set.shortcut.edit": "Record",
    "set.shortcut.editing": "Stop",
    "set.shortcut.enabled": "On",
    "set.shortcut.disabled": "Off",
    "set.shortcut.disableTip": "Click to enable / disable this shortcut",
    "set.api": "Local API",
    "set.api.off": "Disabled",
    "set.api.on": "Enabled · {url}",
    "set.api.doc": "Docs",
    "set.api.doc.link": "API Docs URL",
    "shortcut.recording": "Press a shortcut combo (up to 3 keys)…",
    "shortcut.invalid": "A shortcut combo can have at most 3 keys; not saved.",
    "shortcut.captured": "Shortcut saved: {combo}",
    "batch.ctx.delete": "Delete batch",
    "dialog.deleteBatch.title": "Delete data batch",
    "dialog.deleteBatch.body": "Delete batch \"{batch}\"? Its data and associated bindings will be removed permanently.",
    "dialog.deleteBatch.confirm": "Delete",
    "dialog.deleteBatch.cancel": "Cancel",
    "msg.batchDeleted": "Batch deleted: {batch}",
    "msg.batchDeleteFailed": "Delete failed: {msg}",
    "msg.apiToggleFail": "API toggle failed: {err}",
    "closeModal.title": "Close App",
    "closeModal.body": "Choose an action:",
    "closeModal.minimize": "Hide Icon",
    "closeModal.closeApp": "Close",
    "closeModal.remember": "Remember",
    "tip.info": "About this tool",
    "about.title": "About",
    "about.github": "GitHub Repository",
    "about.version": "Version",
    "about.author": "Author",
    "about.copyright": "Copyright",
    "about.close": "Close"
  }
};
